import type { Config } from 'tailwindcss'

export default {
  content: [
    './app/components/**/*.{vue,js,ts}',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './app/**/*.vue',
  ],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--color-canvas)',
        'canvas-muted': 'var(--color-canvas-muted)',
        'canvas-subtle': 'var(--color-canvas-subtle)',
        surface: 'var(--color-surface)',
        'surface-elevated': 'var(--color-surface-elevated)',
        edge: 'var(--color-border)',
        'edge-strong': 'var(--color-border-strong)',
        ink: 'var(--color-ink)',
        'ink-secondary': 'var(--color-ink-secondary)',
        'ink-muted': 'var(--color-ink-muted)',
        'ink-subtle': 'var(--color-ink-subtle)',
        'ink-faint': 'var(--color-ink-faint)',
        brand: 'var(--color-primary)',
        'brand-hover': 'var(--color-primary-hover)',
        'on-brand': 'var(--color-primary-ink)',
        'nav-surface': 'var(--color-nav-bg)',
        'nav-edge': 'var(--color-nav-border)',
        'footer-canvas': 'var(--color-footer-bg)',
        'auth-canvas': 'var(--color-auth-canvas)',
        'input-edge': 'var(--color-input-border)',
        'input-surface': 'var(--color-input-bg)',
        'faq-muted': 'var(--color-faq-muted)',
        link: 'var(--color-link)',
        'link-hover': 'var(--color-link-hover)',
        'pro-amber': 'var(--color-pro-badge)',
        'pro-cta': 'var(--color-pro-cta)',
        'pro-cta-text': 'var(--color-pro-cta-text)',
        'btn-muted': 'var(--color-secondary-btn)',
        'btn-muted-hover': 'var(--color-secondary-btn-hover)',
        'social-threads': 'var(--color-threads-btn)',
        'social-threads-hover': 'var(--color-threads-btn-hover)',
        'table-head': 'var(--color-table-header-bg)',
        'table-line': 'var(--color-table-border)',
        success: 'var(--color-success)',
        'stat-from': 'var(--color-stat-from)',
        'stat-to': 'var(--color-stat-to)',
        'plan-free-border': 'var(--color-plan-free-border)',
        'plan-free-hr': 'var(--color-plan-free-hr)',
        'plan-free-title': 'var(--color-plan-free-title)',
        'plan-pro-bg': 'var(--color-plan-pro-bg)',
        'plan-pro-border': 'var(--color-plan-pro-border)',
        'plan-pro-hr': 'var(--color-plan-pro-hr)',
        'plan-plat-border': 'var(--color-plan-plat-border)',
        'plan-toggle-bg': 'var(--color-plan-toggle-bg)',
        'tier-basic': 'var(--color-tier-basic)',
        'tier-pro': 'var(--color-tier-pro)',
        'tier-plat': 'var(--color-tier-plat)',
        'accent-border': 'var(--color-hover-border-primary)',
        'btn-dark-hover': 'var(--color-btn-dark-hover)',
        eyebrow: 'var(--color-eyebrow)',
      },
    },
  },
} satisfies Config
